# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66c4a2e065abe03fb0ba4c2ad37f56aa266e08a8edf65355959ce7d7dd9453c9d04810d770c9962cdcfda68c8bcc137786647500069b63545d4eb439374b1f8e

test:
  secret_key_base: f9393c8783aaf4f6b72efd457fc6d8175aa57d1b424a0107084be92cdaebe25f8bf1fe39f0a32716c6a6101cca88d3e32ba8dc7667007826ae37691dd3f4afe3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
